"""transaction sem o lambda

Revision ID: 17fca5233f37
Revises: 527d010e8820
Create Date: 2023-09-19 20:17:29.027180

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '17fca5233f37'
down_revision = '527d010e8820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balance', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance', type_='unique')
    # ### end Alembic commands ###
